sudo: false
language: csharp 

install:
    - nuget restore AppSettingsByConvention.sln
    - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
    - xbuild /p:Configuration=Release AppSettingsByConvention.sln
    - mono ./testrunner/NUnit.Runners.3.0.1/tools/nunit-console.exe ./AppSettingsByConventionTests/bin/Release/AppSettingsByConventionTests.dll